[[edge_functions]]
  path = "/"
  function = "gallery"

[[edge_functions]]
  path = "/gallery/*"
  function = "authGate"

[[edge_functions]]
  path = "/img/*"
  excludedPath = "/img/public/*"
  function = "authGate"
