name: Update data submodule

on:
  workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: Write ssh key
      run: |
          echo "$DATA_DEPLOY_KEY" >> deploykey
      shell: bash
      env:
        DATA_DEPLOY_KEY: ${{secrets.DATA_DEPLOY_KEY}}
        
    - name: Clone submodule
      run: |
        rm -rf data
        git rm data
        git submodule add --force --depth 1 git@github.com:freyacodes/freyaphotos-data.git data
      env:
        GIT_SSH_COMMAND: "ssh -i deploykey"

    - name: Commit & push changes
      run: |
        git config --global user.name "Freya Arbjerg"
        git config --global user.email "freya@arbjerg.dev"
        git commit -am "Update data submodule"
        git push
