name: Update submodules

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Commit & push changes
      run: |
        git config --global user.name "Freya Arbjerg"
        git config --global user.email "freya@arbjerg.dev"
        git commit -am "Update data submodule"
        git push
